project:
  name: customer-churn-analysis-prediction
  artifacts_dir: artifacts

data:
  path: Data/Telco_Customer_Churn_Dataset  (1).csv
  id_column: customerID
  target: Churn
  positive_label: "Yes"
  negative_label: "No"
  test_size: 0.2
  random_state: 42

training:
  models:
    - name: logistic_regression
      estimator: logistic_regression
      params:
        C: [0.1, 1.0, 10.0]
        penalty: ["l2"]
        solver: ["lbfgs"]
        max_iter: [1000]
    - name: random_forest
      estimator: random_forest
      params:
        n_estimators: [200, 500]
        max_depth: [null, 10, 20]
        min_samples_split: [2, 5]
    - name: xgboost
      estimator: xgboost
      params:
        n_estimators: [300]
        max_depth: [3, 5]
        learning_rate: [0.1]
        subsample: [0.8]
        colsample_bytree: [0.8]
    - name: lightgbm
      estimator: lightgbm
      params:
        n_estimators: [300]
        max_depth: [-1, 10]
        learning_rate: [0.1]
        subsample: [0.8]
        colsample_bytree: [0.8]

metrics:
  primary: roc_auc
  report: reports/metrics.json


