- hosts: all
  become: true
  vars:
    repo_dir: /opt/ai-app
  tasks:
    - name: Install prerequisites
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release"]
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable

    - name: Install Docker
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
        update_cache: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: "{{ repo_dir }}"
        state: directory

    - name: Sync repository (assumes git already available)
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_dir }}"
        version: main

    - name: Compose up
      community.docker.docker_compose_v2:
        project_src: "{{ repo_dir }}"
        state: present

