name: CI-CD
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest -f Dockerfile.api .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -f Dockerfile.frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Deploy via SSH + Ansible
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y ansible git
            if [ -d /opt/ai-app ]; then sudo rm -rf /opt/ai-app; fi
            # Clean up corrupted Docker repository files from previous failed attempts
            sudo rm -f /etc/apt/sources.list.d/docker.list
            sudo rm -f /etc/apt/keyrings/docker.gpg
            sudo git clone https://github.com/${{ github.repository }}.git /opt/ai-app --depth 1
            cd /opt/ai-app
            sudo ansible-galaxy collection install community.docker
            sudo ansible-playbook -i "localhost," -e "git_repo_url=https://github.com/${{ github.repository }}.git" /opt/ai-app/ansible/playbook.yml --connection=local

